# Generated by Django 2.0 on 2021-04-10 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20171017_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='course',
            field=models.ForeignKey(default=1, on_delete=None, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='course',
            field=models.ForeignKey(default=1, on_delete=None, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='course',
            field=models.ForeignKey(default=1, on_delete=None, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
