# Generated by Django 2.0 on 2021-04-10 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20171022_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=-1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=None, to='instructor.Course'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=None, to='instructor.Assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
